<?php

define('ATEST_AUTHOR', 'Andy Truong');

class At_Base_Test_Class {
  private $name = 'Andy Truong';

  public function __construct($name = NULL) {
    if (!is_null($name)) {
      $this->name = $name;
    }
  }

  public function __invoke() {}

  public function foo() {}

  public function hi($name) {
    return $this->hello($name);
  }

  public function helloProperty() {
    return "Hello {$this->name}";
  }

  public function hello($name = 'Andy Truong') {
    return "Hello {$name}";
  }

  public static function helloStatic($name = 'Andy Truong') {
    return "Hello {$name}";
  }

  public function getVariables() {
    return atest_variables();
  }

  public static function staticGetVariables() {
    return atest_variables();
  }
}

function atest_base_hello($name = 'Andy Truong') {
  return "Hello {$name}";
}

function atest_base_hello_node($args = array()) {
  if (isset($args['#node'])) {
    $node = $args['#node'];
    $title = $node->title;
    return "Hello {$title}";
  }
  else {
    return "There is no node";
  }
}

function atest_base_content_render_condition_callback($value = FALSE) {
  return !empty($value);
}

function atest_base_content_render_condition_sys_arg_callback($node) {
  if (is_object($node) && $node->title == 'Render me') {
    return TRUE;
  }
  return FALSE;
}

/**
 * @see Drupal\at_base\Tests\Unit\ServiceContentRenderTest::testDynamicVariables
 */
function atest_variables() {
  return array(
    'name' => ATEST_AUTHOR,
  );
}

/**
 * Implements hook_views_api().
 */
function atest_base_views_api($module, $api) {
  if ($module == 'views' && $api == 'views_default') {
    return array('version' => 2);
  }
}
